package fr.scabois.scabotheque.enums;

public enum ExportFileType {
    TYPE_LIST_ADHERENT, TYPE_LIST_ADHERENT_INTERNE, TYPE_LIST_FOURNISSEUR,
    TYPE_LIST_CONTACT, TYPE_LIST_CONTACT_RETRAITE, TYPE_LIST_CONTACT_CLUB_FEMME;

}
