package fr.scabois.scabotheque.enums;

public enum PageType {
  DASHBOARD,
  ADHERENT_ACTIVITE, ADHERENT_ADMINISTRATIF, ADHERENT_ARTIPOLE, ADHERENT_DETAIL, ADHERENT_EXPLOITATION,
  ADHERENT_INFORMATIQUE, ADHERENT_CRM, ADHERENT_CAPITAL_SOCIAL, CREATE_ADHERENT,
  GESTION_AGENCE, GESTION_COMMUNE, GESTION_FOURNISSEUR, GESTION_METIER, GESTION_POLE, GESTION_PRODUIT,
  GESTION_SECTEUR, GESTION_USERS, ANALYSE,
  LIENS_UTILS, LIST_ADHERENT, LIST_CONTACT, LIST_FOURNISSEUR, TABLES_BASE, GESTION_ROLES_EOLAS, LOGISTIQUE_TOURNEE;
}
