package fr.scabois.scabotheque.enums;

public enum PageType {
    ADHERENT_ACTIVITE, ADHERENT_ADMINISTRATIF, ADHERENT_ARTIPOLE, ADHERENT_DETAIL, ADHERENT_EXPLOITATION,
    ADHERENT_INFORMATIQUE, AJOUT_COURSES, CREATE_ADHERENT, GESTION_AGENCE, GESTION_COMMUNE, GESTION_FOURNISSEUR,
    GESTION_METIER, GESTION_POLE, GESTION_PRODUIT, GESTION_SECTEUR, GESTION_USERS, LIENS_UTILS, LIST_ADHERENT,
    LISTE_COURSES, MODIF_COURSES, SUPPRESSION_COURSES, TABLES_BASE
}
