package fr.scabois.scabotheque.enums;

public enum PageType {
  DASHBOARD,
  AA_ADMIN, AA_ACCUEIL, AA_ARTISAN_ARTIPOLE, AA_EMPLACEMENT, AA_JE_CHERCHEUN_ARTISAN, AA_INSPIRATIONS, AA_NOS_METIERS, AA_SALLE_EXPOSITION, AA_CATEGORIES, AA_PHOTO, AA_METIER, AA_ACTUALITES,
  ADHERENT_ACTIVITE, ADHERENT_ADMINISTRATIF, ADHERENT_ARTIPOLE, ADHERENT_DETAIL, ADHERENT_EXPLOITATION,
  ADHERENT_INFORMATIQUE, ADHERENT_CRM, ADHERENT_CAPITAL_SOCIAL, CREATE_ADHERENT,
  GESTION_AGENCE, GESTION_COMMUNE, GESTION_FOURNISSEUR, GESTION_METIER, GESTION_POLE, GESTION_PRODUIT,
  GESTION_SECTEUR, GESTION_USERS, ANALYSE,
  LIENS_UTILS, LIST_ADHERENT, LIST_CONTACT, LIST_CONTACT_RETRAITE, LIST_CONTACT_CLUB_FEMMES, LIST_FOURNISSEUR, TABLES_BASE, GESTION_ROLES_EOLAS, LOGISTIQUE_TOURNEE;
}
